### ISSUE TITLE
Add async method

### ISSUE THREAD

**Issue by aminya** [stefanpenner/resolve-package-path#36] opened 2021-04-29 06:29 UTC
This package lacks an async method and all the calls to `fs` are sync.

**Comment by stefanpenner** [comment] 2021-05-10 23:08
@aminya this was by design, our needs where serial throughput performance, not concurrent performance.

I would be open to a maintainable PR that exposes an async variant.

**Comment by aminya** [comment] 2021-05-18 21:25
Should we make the code `async`, and use [make-synchronous](https://www.npmjs.com/package/make-synchronous) or [deasync](https://www.npmjs.com/package/deasync) to keep the code backward compatible?

**Comment by stefanpenner** [comment] 2021-06-03 15:56
@aminya Although it would improve maintainability and share code between the two approaches I would recommend against that for the following reasons.

1) deasync uses a native module, decreasing portability of this project.
2) make-synchronous uses subprocess, which both decreases throughput and debuggability.

Unfortunately both of these approaches would impede this projects primary goals. Most likely we need a parallel implementations, or a form of refactoring that enables sharing while decoupling the IO.

---

Out of curiosity do you have a specific use-case where you need this to be async? This may help me better understand the given use-case, and come up with a good approach.

**Comment by stefanpenner** [comment] 2021-09-13 23:16
This has been sitting for a minute now, I'll be closing this. We can continue to have the conversation here, and if the above can be addressed we can gladly reopen.

**Closed as completed by stefanpenner** 2021-09-13 23:16 UTC
Labels: enhancement, help wanted
